# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protoc import loader_pb2 as protoc_dot_loader__pb2


class ImageLoaderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.load = channel.unary_unary(
                '/ImageLoader/load',
                request_serializer=protoc_dot_loader__pb2.ImageLoaderRequest.SerializeToString,
                response_deserializer=protoc_dot_loader__pb2.ImageLoaderResponse.FromString,
                )


class ImageLoaderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def load(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageLoaderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'load': grpc.unary_unary_rpc_method_handler(
                    servicer.load,
                    request_deserializer=protoc_dot_loader__pb2.ImageLoaderRequest.FromString,
                    response_serializer=protoc_dot_loader__pb2.ImageLoaderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageLoader', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageLoader(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def load(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImageLoader/load',
            protoc_dot_loader__pb2.ImageLoaderRequest.SerializeToString,
            protoc_dot_loader__pb2.ImageLoaderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
