# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/streaming.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protoc/streaming.proto\" \n\x10StreamingRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"%\n\x11StreamingResponse\x12\x10\n\x08response\x18\x01 \x01(\t2>\n\tStreaming\x12\x31\n\x04\x63\x61ll\x12\x11.StreamingRequest\x1a\x12.StreamingResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protoc.streaming_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STREAMINGREQUEST']._serialized_start=26
  _globals['_STREAMINGREQUEST']._serialized_end=58
  _globals['_STREAMINGRESPONSE']._serialized_start=60
  _globals['_STREAMINGRESPONSE']._serialized_end=97
  _globals['_STREAMING']._serialized_start=99
  _globals['_STREAMING']._serialized_end=161
# @@protoc_insertion_point(module_scope)
