# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/trainer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protoc/trainer.proto\"#\n\x13ModelTrainerRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"#\n\x14ModelTrainerResponse\x12\x0b\n\x03log\x18\x01 \x01(\t2H\n\x0cModelTrainer\x12\x38\n\x05train\x12\x14.ModelTrainerRequest\x1a\x15.ModelTrainerResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protoc.trainer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MODELTRAINERREQUEST']._serialized_start=24
  _globals['_MODELTRAINERREQUEST']._serialized_end=59
  _globals['_MODELTRAINERRESPONSE']._serialized_start=61
  _globals['_MODELTRAINERRESPONSE']._serialized_end=96
  _globals['_MODELTRAINER']._serialized_start=98
  _globals['_MODELTRAINER']._serialized_end=170
# @@protoc_insertion_point(module_scope)
