# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protoc import trainer_pb2 as protoc_dot_trainer__pb2


class ModelTrainerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.train = channel.unary_stream(
                '/ModelTrainer/train',
                request_serializer=protoc_dot_trainer__pb2.ModelTrainerRequest.SerializeToString,
                response_deserializer=protoc_dot_trainer__pb2.ModelTrainerResponse.FromString,
                )


class ModelTrainerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelTrainerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'train': grpc.unary_stream_rpc_method_handler(
                    servicer.train,
                    request_deserializer=protoc_dot_trainer__pb2.ModelTrainerRequest.FromString,
                    response_serializer=protoc_dot_trainer__pb2.ModelTrainerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ModelTrainer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModelTrainer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ModelTrainer/train',
            protoc_dot_trainer__pb2.ModelTrainerRequest.SerializeToString,
            protoc_dot_trainer__pb2.ModelTrainerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
